### ISSUE TITLE
documentation v1.1.0-SNAPSHOT should be default or v1.0.0 instructions should be fixed

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/knative-tutorial#109]
01-basics has been renamed, but the documentation refers to it: https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.0.0/01basic-fundas.html#basics-deploy-service

**Comment by kameshsampath** [comment]
@rafabene all changes are part of https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.1.0-SNAPSHOT, i will be releasing v1.1.0 next week. I made v1.0.0 ( Knative v0.3.0) as default as v0.4.0 has some breaking changes and I thought to have a stable version as default

**Comment by rafabene** [comment]
If I follow v1.0.0  ( https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.0.0/setup.html ) the folder is inexistent. Given your explanation, the fix should be:

Git clone -b v1.0.0 <repo> in the following instruction: https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.0.0/setup.html#download-tutorial-sources

**Comment by kameshsampath** [comment]
No, please use the 1.1.0-SNAPSHOT version that’s the latest where the alignment is done correctly

**Comment by rafabene** [comment]
Ok. So shouldn't the URL https://redhat-developer-demos.github.io/knative-tutorial open 1.1.0-SNAPSHOT as default? I just followed the README.md and landed at 1.0.0 with a non-working instruction.

**Comment by kameshsampath** [comment]
I will soon do away with it after 1.1.0 relase. Sorry for some issues :(

**Comment by rafabene** [comment]
Even using 1.1.0-SNAPSHOT I can't follow the instructions as it also points to 01-basics at https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.1.0-SNAPSHOT/02-basic-fundas.html#basics-deploy-service

**Comment by kameshsampath** [comment]
Just tried the link . am not able reproduce it :( .. can clear your local cache .. sometimes that might have some issue.

**Comment by rafabene** [comment]
It's not a cache issue. Look here in the git repo: https://github.com/redhat-developer-demos/knative-tutorial/blob/master/documentation/modules/ROOT/pages/02-basic-fundas.adoc#deploy-service

Is shows 01-basics in 02-basic-fundas.adoc

**Comment by kameshsampath** [comment]
ah i got it now .. will fix it .. thanks

**Comment by rafabene** [comment]
The same seems to happen in every .adoc btw

**Comment by kameshsampath** [comment]
am fixing everywhere,. you should see in next update

**Comment by rafabene** [comment]
Tks ;)

**Comment by kameshsampath** [comment]
Fixed via #114 , @rafabene  can verify now ? I also made v1.1.0-SNAPSHOT as default site

**Comment by kameshsampath** [comment]
@rafabene  - closing this as we have different versioning aligned with Knative
