### ISSUE TITLE
Create a link in the documentation to files

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/knative-tutorial#11]
When mentioning a file, you should use a HTTP link to the file on Github, that way, it's easy to see the content of that file.

This was made at [Istio Tutorial](https://redhat-developer-demos.github.io/istio-tutorial/istio-tutorial/1.0.x/4simple-routerules.html#deployrecommendationv2)

**Comment by kameshsampath** [comment]
@rafabene  WIP

**Comment by kameshsampath** [comment]
@rafabene  -  i have fixed this in the latest tutorial documentation. Can you please verify and confirm.

**Comment by rafabene** [comment]
With so many changes, it's better merge and I try with a live documentation.
