### ISSUE TITLE
Create the TUTORIAL_HOME env var

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/knative-tutorial#113]
The env var TUTORIAL_HOME should be created using the command:

> **export TUTORIAL_HOME=\`pwd\`**

The instruction to created this env var should be after git clone ... ; cd ...
at https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.1.0-SNAPSHOT/01-setup.html#download-tutorial-sources

**Comment by kameshsampath** [comment]
done!
