### ISSUE TITLE
running the tutorial on OCP4

### ISSUE THREAD

**Issue by piggyvenus** [redhat-developer-demos/knative-tutorial#127]
**Describe the bug**
On 02-basic (https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.1.0-SNAPSHOT/02-basic-fundas.html#basics-deploy-service), got my docker built locally and called dev.local/rhdevelopers/greeter. When I do ’oc apply -f service.yaml, it does not know how to pick up the dev.local/rhdevelopers/greeter images from the local docker on my laptop. If I push the docker image to dockerhub and update the image name, the service will get deploy but not from local build as shown in the lab.

**To Reproduce**
1. install OCP4 
2. install knative on OCP4
3. connect to the cluster via oc remotely 
4. after building the docker image locally
5. service will not deploy because the image is not available to pull.
It will work if I push to dockerhub and change service.yaml to match the name in dockerhub.

**Expected behavior**
Expected to build and deploy on OCP4. 

**Desktop (please complete the following information):**
 - OS: client (mac)
 - OCP4 Cluster version is 4.0.0-0.9
Client Version: version.Info{Major:"4", Minor:"0+", GitVersion:"v4.0.22", GitCommit:"219bbe2f0c", GitTreeState:"", BuildDate:"2019-03-10T22:23:11Z", GoVersion:"", Compiler:"", Platform:""}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+0ba401e", GitCommit:"0ba401e", GitTreeState:"clean", BuildDate:"2019-03-31T22:28:12Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kameshsampath** [comment]
@piggyvenus  for all external cluster builders its expected the service images are hosted in the remote repos. The v0.5.0 release that am planning later next week will have a remote yamls  that can use remote images than you building it locally for external cluster

**Comment by kameshsampath** [comment]
@piggyvenus I fixed this all in the latest and tested with OCP 4.1 and Knative Serving Operator v0.6.0 . All good now, we have both local and remote yamls. Closing for now, please feel free to open If you feel you need to.
