### ISSUE TITLE
copyToClipboard directives in rendered HTML

### ISSUE THREAD

**Issue by alanconway** [redhat-developer-demos/knative-tutorial#130]
**Describe the bug**
I see markup like `copyToClipboard::run-install-istio[]` in rendered HTML when I build & render the tutorial locally.

**To Reproduce**
1. clone https://github.com/redhat-developer-demos/knative-tutorial/
2. run `gulp`
3. open http://localhost:5353/knative-tutorial/v1.1.0-SNAPSHOT/01-setup.html
4. search in page for "copyToClipboard"

**Expected behavior**
Clipboard functionality, no visilble markup.

**Screenshots**
![image](https://user-images.githubusercontent.com/7780958/55890704-2e777400-5b81-11e9-8803-c669e9a88aa3.png)

**Desktop (please complete the following information):**
 - OS: fedora 29
 - Browser: Google Chrome | 73.0.3683.103 (Official Build) (64-bit)

**Additional context**

$ npm -g list | grep ascii
│ ├─┬ @antora/asciidoc-loader@2.0.0
│ │ └─┬ asciidoctor.js@1.5.9
│ │ └── @antora/asciidoc-loader@2.0.0 deduped
│ │ └── @antora/asciidoc-loader@2.0.0 deduped
│ │ ├── @antora/asciidoc-loader@2.0.0 deduped

**Comment by kameshsampath** [comment]
I see its fixed and aligned now.  Please verify in the latest release and will keep it open until then

**Comment by alanconway** [comment]
I can confirm it works on latest release.
