### ISSUE TITLE
Build template fail 

### ISSUE THREAD

**Issue by piggyvenus** [redhat-developer-demos/knative-tutorial#132]
**Describe the bug**
Using build template to build, the build completed, but I get the following error in "build-step-build-and-push" after build and caused the build failed

log from build-step-build-and-push:
[INFO] Installing /workspace/java/springboot/target/greeter.jar to /root/.m2/repository/com/example/greeter/0.0.1/greeter-0.0.1.jar
[INFO] Installing /workspace/java/springboot/pom.xml to /root/.m2/repository/com/example/greeter/0.0.1/greeter-0.0.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.394 s
[INFO] Finished at: 2019-04-10T16:22:33Z
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "native" could not be activated because it does not exist.
cp: cannot stat 'target/greeter-runner': No such file or directory

**To Reproduce**
1. create the build template that provided by the tutorial in #06 exercise
2. Use this following as the service-with-build-template.yaml
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-greeter
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              revision: v0.0.2
              url: https://github.com/redhat-developer-demos/knative-tutorial-greeter.git
          template:
            arguments:
            - name: IMAGE
              value: docker.io/piggyvenus/greeter:0.0.2
            - name: CONTEXT_DIR
              value: /workspace/java/springboot
            name: build-java-maven
          timeout: 20m
      revisionTemplate:
        metadata:
          labels:
            app: event-greeter
        spec:
          container:
            image: docker.io/piggyvenus/greeter:0.0.2
3. Then failed with the error that I provided.
4. See error for the build-step-build-and-push container
[INFO] Installing /workspace/java/springboot/target/greeter.jar to /root/.m2/repository/com/example/greeter/0.0.1/greeter-0.0.1.jar
[INFO] Installing /workspace/java/springboot/pom.xml to /root/.m2/repository/com/example/greeter/0.0.1/greeter-0.0.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.394 s
[INFO] Finished at: 2019-04-10T16:22:33Z
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "native" could not be activated because it does not exist.
cp: cannot stat 'target/greeter-runner': No such file or directory

--------kubectl describe pod ----
build-step-build-and-push:
    Container ID:  docker://033c31d0231108be8d7d3f6e3a0dbd02967ac0684f2834e517d9364487734991
    Image:         quay.io/rhdevelopers/quarkus-java-builder
    Image ID:      docker-pullable://quay.io/rhdevelopers/quarkus-java-builder@sha256:c0f4bd8ef3313a8c764f4cff0e8b8398a182065f08010d5eae78e563dcf90463
    Port:          <none>
    Host Port:     <none>
    Args:
      /usr/local/bin/buildah.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 10 Apr 2019 09:21:29 -0700
      Finished:     Wed, 10 Apr 2019 09:22:36 -0700
    Ready:          False

**Desktop (please complete the following information):**
 - OS: Mac 
 - Version Darwin MacBook-Pro 18.2.0
- minikube version: v1.0.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"} 

**Additional context**

**Comment by kameshsampath** [comment]
@piggyvenus the springboot does not have `-Pnative` profile. 

Can you try update the  `event-greeter-build.yaml` (https://github.com/redhat-developer-demos/knative-tutorial/blob/master/05-build/knative/event-greeter-build.yaml#L12-L13) with `/usr/local/bin/maven-buildah.sh` which does the normal maven build and package of application and pushing to container repo.

Please try and let me now.

**Comment by kameshsampath** [comment]
@piggyvenus am closing this, please open a issue if you encounter other issues.
