### ISSUE TITLE
knative-tutorial is out of sync with knative-tutorial-greeter/java/quarkus

### ISSUE THREAD

**Issue by alanconway** [redhat-developer-demos/knative-tutorial#137]
**Describe the bug**

The build instructions for the greeter example are completely different between the main tutorial repo and the greeter repo. Even if both are correct it will be hard to keep them in sync. Suggest keeping all build instructions in the -greeter repo and linking from the main tutorial.

knative-tutorial/work/knative-tutorial-greeter/java/quarkus/README.adoc
```
mvn -Dcontainer.registry.url='https://index.docker.io' \ #<1>
-Dcontainer.registry.user='<your docker hub user>' \ #<2>
-Dcontainer.registry.password='<your docker hub password>' \#<3>
-Dgit.source.revision='master' \#<4>
-Dgit.source.repo.url='https://github.com/redhat-devloper-demos/knative-tutorial-greeter.git'
\#<5> -Dapp.container.image='docker.io/<your-repo>/quarkus-greeter'
\#<6> clean process-resources
```  
knative-tutorial/documentation/modules/ROOT/pages/_partials/build-containers.adoc
```
cd knative-tutorial-greeter/java/quarkus
./mvnw clean package
docker build -t dev.local/rhdevelopers/greeter:0.0.1  -f Dockerfile.all .
```

**Comment by kameshsampath** [comment]
thanks @alanconway  - updated the demo sources to point to the tutorial.
