### ISSUE TITLE
Alternative explanations break up the flow of the tutorial.

### ISSUE THREAD

**Issue by alanconway** [redhat-developer-demos/knative-tutorial#139]
**Describe the bug**

Each step of the tutorial has 2 or 3 different sets of instructions for minikube/minishift/openshift.
It is hard to read, in particular general comments after the alternatives are easy to overlook, thinking they are part of the last alternative.

Suggestions
* Use tabs so only one alternative is visible at a time.
* Factor out the variations and explain them once at the start, so we don't need alternatives later.

The main variations look like they could be factored out:
  * How to get the IP address - it's the same for each example.
  * Using oc vs. kubectl - we could just explain that all the commands can be one with either kubectl or oc, and show kubectl in all the examples.

**Comment by kameshsampath** [comment]
I am working on the extension to add tabs to the doc, may be we can release as part of 0.5.0

**Comment by syedriko** [comment]
May be this https://book.kubebuilder.io/getting_started/installation_and_setup.html can be a source of inspiration. There's a Mac/Linux toggle in the "title bar" of the page that changes the OS-specific parts of the code on the page.

**Comment by kameshsampath** [comment]
yes am looking at https://docs.couchbase.com/sync-gateway/2.1/getting-started.html which is based on Asciidoc

**Comment by kameshsampath** [comment]
i have added tabs now to the tutorial, will be part of v0.5.0 release. That should solve this issue. User can then take a kubectl + minikube path or oc + minishift path

**Comment by alanconway** [comment]
That sounds like the right solution

**Comment by kameshsampath** [comment]
updated in latest tutorial. closing this for now.
