### ISSUE TITLE
Doing the tutorial on a real cluster

### ISSUE THREAD

**Issue by alanconway** [redhat-developer-demos/knative-tutorial#140]
**Describe the bug**

I ran the tutorial on a bare-metal, 3 node cluster: https://github.com/alanconway/occ
There are a number of differences from minikube/minishift. If the tutorial only targets mini* use then this may not matter, but if we want to support users on real clusters here are some points:

### NodePort vs. LoadBalance

For NodePort on a real cluster, use `get nodes` for the IP host, instead of a mini* command.

LoadBalance is likely to be supported on a real cluster, and may be worth showing in the tutorial.
For example, host/port of a LoadBalanced ISTIO:
```
$ export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
$ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
$ export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
```
(from https://preliminary.istio.io/docs/tasks/traffic-management/ingress.html#determining-the-ingress-ip-and-ports)

### Docker registry 

eval `$(mini* docker-env)` only works on a single-node cluster with a single dockerd.
On a real cluster you need to pull images from an external registry.

I set up my cluster to pull from my dockerhub account (see https://github.com/alanconway/occ#use-a-private-docker-registry), users that don't control their cluster would have to use some registry allowed by the cluster.

Here's how I tag/push the greeter example and modify server.yaml to pull it:
```
DOCKER_USER="<your docker user name>"
docker login -u $DOCKER_USER
docker tag dev.local/rhdevelopers/greeter:0.0.1 $DOCKER_USER/greeter:0.0.1
docker push $DOCKER_USER/greeter:0.0.1
sed "s|dev.local/rhdevelopers|$DOCKER_USER|" service.yaml > service2.yaml
```

**Comment by kameshsampath** [comment]
@alanconway  - if you check the latest docs I have removed docker stuff from OpenShift and made it OpenShift 4.x only. All the images now use the sample images from quay.io/redhat-developer-demos so these steps are obsolete now. Closing this now and please open it if you feel we need to address something specific
