### ISSUE TITLE
Describe how to make ingressgateway accessible on Minikube

### ISSUE THREAD

**Issue by mgencur** [redhat-developer-demos/knative-tutorial#141]
**Describe the bug**
The chapter at https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/0.4.0/01-setup.html#install-knative-istio describes installation of Istio/Knative on Minikube. 
The current approach is missing one step which would make the istio-ingressgateway accessible from the host.
One way to achieve that is by replacing LoadBalancer with NodePort:
`wget -O - https://github.com/knative/serving/releases/download/v0.4.0/istio.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | kubectl apply -f -
`
and then using the this address to access Knative: `$(minikube ip):30663` where 30663 is the nodePort value of "http2" port on istio-ingressgateway. This port is automatically assigned and might be different each time.

Another way might be using `minikube tunnel` but I haven't explored this way.

**To Reproduce**

**Expected behavior**
The istio-ingressgateway is accessible from the host.

**Comment by kameshsampath** [comment]
@mgencur - I feel thats more of a minikube thing than what we need to do, I right now have consistent way of pulling the ingress. So closing it for now. If you still feel its needed then please reopen.
