### ISSUE TITLE
Eventing section references unexisting tag for knative-tutorial-greeter

### ISSUE THREAD

**Issue by aliok** [redhat-developer-demos/knative-tutorial#144]
In eventing section there is this suggestion:

> If you have skipped the Build or Build Templates and dont have the container image of event-greeter; then you can update the Knative serving service to use the pre-built event-greeter image available at quay.io/rhdevelopers/knative-tutorial-greeter:0.0.1

At line [1] doc suggests using `quay.io/rhdevelopers/knative-tutorial-greeter:0.0.1` but the tag doesn't exist [2].

Using `quarkus` tag worked fine though.

1. https://github.com/redhat-developer-demos/knative-tutorial/blame/0df86d2fda5cf4544e807cf1879c966a3b282018/documentation/modules/ROOT/pages/06-eventing/eventing-src-svc.adoc#L129
2. https://quay.io/repository/rhdevelopers/knative-tutorial-greeter?tab=tags

@kameshsampath I can send a super quick PR to update this tag to `quarkus` if you don't want to use `0.0.1` kind of tags anymore.

**Comment by kameshsampath** [comment]
fixed in latest updates
