### ISSUE TITLE
Reduce repetition of Build Containers instructions

### ISSUE THREAD

**Issue by alanconway** [redhat-developer-demos/knative-tutorial#145]
**Describe the bug**

Each section of the tutorial repeats  an identical "Build Containers" section. 
It's distracting if you are working thru the tutorial in order and keep seeing steps you have already taken. 

Suggest putting this section only in 02-basics, and providing a link from the start of each other section, something like "if you haven't already built the example containers, go _here_" to reduce repetition.

**Comment by kameshsampath** [comment]
@alanconway  the reason for the repetition is sometimes developers jump chapters and might skip critical steps. They will then wonder why thats not working.. I have added a note to say skip if already done
