### ISSUE TITLE
Docs: cron job source service pod is not created when there is no sink service

### ISSUE THREAD

**Issue by aliok** [redhat-developer-demos/knative-tutorial#147]
**Describe the bug**
In the ["Eventing Source to Service"](https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/0.4.0/06-eventing/eventing-src-svc.html) section of the docs, it is stated that "*The cronjob source also creates a service pod*", after creating the event source. However, in my experiments, the pod is only created when the [sink service](https://github.com/redhat-developer-demos/knative-tutorial/blob/0df86d2fda5cf4544e807cf1879c966a3b282018/06-eventing/knative/event-source-svc.yaml#L11) defined in the source definition is created.

I guess it makes sense as Knative would recognize the sink is there and then it would create the source pods. No reason to create them in advance. (@matzew any inputs?)

So, the order of the document should be:
1. Create the sink service
2. Create the cron job source

I tried to fix the order myself but ended up in a Asciidoc problems because the partials used in that section is also used in other places.

I noticed this problem with Knative 0.4.0  and 0.5.0 during https://github.com/redhat-developer-demos/knative-tutorial/pull/146

**Comment by syedriko** [comment]
Yep, that's a known issue. There's a delay in the source recognizing the creation of sink, we're tracking it as https://github.com/knative/eventing-sources/issues/314.

**Comment by aliok** [comment]
@syedriko thanks for the link.

Can you clarify something for me?

Knative should create a pod for the cron job source only when there is a sink service, right?

What I was reporting in ticket was that it was written in the tutorial "The cronjob source creates a service pod" right after the cron job source is created even though there's no sink yet.

**Comment by syedriko** [comment]
That phrase "The cronjob source also creates a service pod," is misleading. "Service" is a heavily overloaded term and using it in just one more meaning like here is not really helping. It's better to call it an "auxiliary pod".

It's really an implementation detail, but the way the cronjob source works at the moment is that a pod that's the real source of events is in fact only launched when the sink is there. If you reorder the parts of the "Source to Service" and go through "Create Sink Service" first and then "Create Event Source", the behavior will match the tutorial.

**Comment by kameshsampath** [comment]
@syedriko  @aliok - I have been thinking on this for v0.5.0 upgrade. The note on the creation of service pod is to tell users that deploying cronjob source will create one cronjob event source pod, may be we can reorder the "Service pod" to be "event source pod"

**Comment by matzew** [comment]
see https://github.com/knative/eventing-sources/issues/314  as well

**Comment by kameshsampath** [comment]
I still feel its good have the same order, infact we can tell the users that containers are initiated only when needed ( typical serverless feature). If we do the other way user cant see it. Closing for now .. If you still need to get it updated send PR to https://github.com/redhat-developer-demos/knative-tutorial-module-basics
