### ISSUE TITLE
Implement tracis CI to automatically build the docs

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/knative-tutorial#15]
Just like https://github.com/redhat-developer-demos/istio-tutorial we should not commit the generated HTML at docs/ folder. Instead, Travis will be responsible to commit the generated docs in the gh-pages branch.

**Comment by kameshsampath** [comment]
what is the issue using docs folder?? In way I feel thats good to have the users having the docs offline.

**Comment by kameshsampath** [comment]
also if you see for knative tutorial the demo projects are in their own repository in rhdevelopers repo

**Comment by kameshsampath** [comment]
having said that am planning to add traivs ci for the repo; IMHO the whole idea of gh-pages for istio-tutorial is because of us having sources and docs in same repo. For this tutorial am trying to have them separate as that is easier to maintain

**Comment by kameshsampath** [comment]
@rafabene  - i still don't understand why you don't want docs folder on master and to be consistent with other tutotrial I have update the ci and using gh-pages now

**Comment by rafabene** [comment]
So I'll change it to implement CI to automatically build the docs and let you handle it, ok?

**Comment by kameshsampath** [comment]
fixed via #21
