### ISSUE TITLE
Provide all-in-one client image

### ISSUE THREAD

**Issue by nobusue** [redhat-developer-demos/knative-tutorial#158]
Current prerequisite is hard to satisfy for Windows users. 
https://knative-workshop.devx.red/knative-tutorial/v0.4.0/01-setup.html#prerequisite

Please consider to provide all-in-one client container image including all prereq tools, or workshop terminal based on JupyterHub:
https://github.com/openshift-labs/workshop-terminal

**Comment by kameshsampath** [comment]
@nobusue  - https://quay.io/repository/rhdevelopers/tutorial-tools?tab=builds  this has all you need. soon will be adding single user che to it
