### ISSUE TITLE
Add link to Knative Operator

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#16]
The Knative Operator is under development and we should point to it for anyone interested in exploring it.  As of this moment, it is only for OCP4 customers.

https://github.com/openshift-cloud-functions/knative-operators

**Comment by kameshsampath** [comment]
the tutorial already has reference to it https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/dev/setup.html#install-knative-openshift
