### ISSUE TITLE
Broken link to docs for Knative installation on OpenShift 3.11

### ISSUE THREAD

**Issue by aliok** [redhat-developer-demos/knative-tutorial#164]
At https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-basics/0.5.0/01-setup.html

"If you need more details about the installation or customizations refer Knative with OpenShift."
with a link to https://github.com/openshift-cloud-functions/Documentation/blob/master/knative-OCP.md

That link is dead. New link for OpenShift 3.11 is here: https://github.com/openshift-cloud-functions/Documentation/blob/master/knative-OCP-311.md

**Comment by kameshsampath** [comment]
@aliok - the latest docs does not use OCP 3.11 at all , moved everything to OCP 4.11. Closing this for now and please feel free to open if you feel you need it.
