### ISSUE TITLE
Incorrect label selector

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#165]
kubectl --namespace knativetutorial get rev \
--label=serving.knative.dev/service=greeter \
--sort-by="{.metadata.creationTimestamp}"

should be
kubectl --namespace knativetutorial get rev \
-l serving.knative.dev/service=greeter \
--sort-by="{.metadata.creationTimestamp}"

**Comment by kameshsampath** [comment]
Both are same one is short and other is long option format.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kameshsampath** [comment]
sorry @burrsutter  got to know that should be `--selector` fixed it
