### ISSUE TITLE
Incorrect docker version when building

### ISSUE THREAD

**Issue by noelo** [redhat-developer-demos/knative-tutorial#171]
**Describe the bug**
All of this running on Mac 10.14.5 

Unable to build image with multi-stage build on minishift.
"Error parsing reference: "quay.io/rhdevelopers/quarkus-java-builder AS builder" is not a valid"

I'm following the instructions on https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-basics/0.5.0/02-basic-fundas.html#basics-prerequisite

It's related to the version of Docker running in Minishift. Details below.

quarkus$ minishift docker-env
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.64.5:2376"
export DOCKER_CERT_PATH="/Users/noelo/.minishift/profiles/knative/certs"
'# Run this command to configure your shell:
'# eval $(minishift docker-env)
quarkus$ eval $(minishift docker-env)
quarkus$ docker build -t dev.local/rhdevelopers/greeter:0.0.1  -f Dockerfile.all .
Sending build context to Docker daemon  24.64MB
Step 1/8 : FROM quay.io/rhdevelopers/quarkus-java-builder AS builder
Error parsing reference: "quay.io/rhdevelopers/quarkus-java-builder AS builder" is not a valid repository/tag: invalid reference format
quarkus$ minishift version
minishift v1.31.0+d06603ea
CDK v3.8.0-2
quarkus$ minishift openshift version
openshift v3.11.82
quarkus$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.26 (downgraded from 1.39)
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          1.13.1
  API version:      1.26 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       07f3374/1.13.1
  Built:            Fri Feb  8 20:24:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false

quarkus$ unset DOCKER_HOST
quarkus$ unset DOCKER_CERT_PATH
quarkus$ unset DOCKER_TLS_VERIFY
quarkus$ docker build -t dev.local/rhdevelopers/greeter:0.0.1  -f Dockerfile.all .
Sending build context to Docker daemon  24.64MB
Step 1/8 : FROM quay.io/rhdevelopers/quarkus-java-builder AS builder
latest: Pulling from rhdevelopers/quarkus-java-builder
01eb078129a0: Pulling fs layer
97f4b0a5e310: Pulling fs layer
8f04eeafd6f4: Download complete
3618fddae0da: Waiting
^C

quarkus$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true

**Comment by kameshsampath** [comment]
minishift does not have Docker version that supports multistage build

**Comment by jameshbarton** [comment]
I encountered this same issue trying to setup the knative tutorial here on macos with minishift.
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-basics/0.5.0/01-setup.html

Is there a reasonable workaround for the multi-stage docker limitation with minishift?  If not, then the tutorial should be updated to reflect that it isn't supported for minishift.  There are currently an entire set of specific minishift directions at the above link, which appear to work fine until the multistage docker build step.

**Comment by kameshsampath** [comment]
I should soon start to update of tutorial to v0.7 will have fresh and updated instructions for OpenShift. 🤞🏻

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
