### ISSUE TITLE
incorrect name for prime-generator

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#180]
**Describe the bug**
https://github.com/redhat-developer-demos/knative-tutorial/blob/master/04-scaling/knative/service-10.yaml#L4

The name of this kservice should be 'prime', not 'greeter' as it is not a greeter-based image.  Also, the prime code should be checked into "apps" so that the reader/student can see actual implementation behind that prime generator code and better understand what parameters it needs to invoke it.

Same issue for this yaml
https://github.com/redhat-developer-demos/knative-tutorial/blob/master/04-scaling/knative/service-min-scale.yaml#L4

**Comment by kameshsampath** [comment]
fixed in #189
