### ISSUE TITLE
source2service, source2subscriber

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#181]
these two examples should be in their own directories.  At this moment, it is confusing to the student to see a bunch of "extra" files that below to one example vs the other.  

We also need to remove the 'knative' subfolder that appears through the chapter/directories as it  adds no value, just another thing the student has to navigate through to get to the files they need.

**Comment by kameshsampath** [comment]
Reorg done based on the cookbook. Not sure if its still valid. Please feel free to reopen.
