### ISSUE TITLE
cronjobsource does not appear until there is a sink

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#184]
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-basics/0.7.x/05-eventing/eventing-src-svc.html#eventing-create-event-source

kubectl apply -n knativetutorial -f event-source-svc.yaml
does not produce a pod
kubectl -n knativetutorial get pods
The above command will return an output like,

NAME                                                          READY     STATUS    RESTARTS   AGE
cronjob-event-greeter-cronjob-source-4v9vq-6bff96b58f-tgrhj   2/2       Running   0      

until the Sink service has been deployed with 
kubectl apply -n knativetutorial -f service.yaml

And the watch logs section should be "in-lined" into this document as it is easy to skip this super critical step because it does not appear as a copy & paste'able command
https://screencast.com/t/uEID5fmQ

**Comment by kameshsampath** [comment]
we have changed the order in the latest .. please validate
