### ISSUE TITLE
Tutorial does not work after following the Operator installation

### ISSUE THREAD

**Issue by fliegera** [redhat-developer-demos/knative-tutorial#190]
I have a OpenShift 4.1.18 cluster on AWS

If I execute the follwing statemant according to the instructions in the tutorial

**oc apply -f "$TUTORIAL_HOME/install/knative-serving/subscription.yaml"**

the following statement **oc get pods -n knative-serving -w** just delivers nothing 

Then after creating a project according to the tutorial this is the output

![tutorial](https://user-images.githubusercontent.com/10500316/66819102-a8c4ee80-ef3e-11e9-8265-25d690c07f7b.PNG)
 
Here another output about requirements that are not met:
![openhiftoperator](https://user-images.githubusercontent.com/10500316/66820504-1540ed00-ef41-11e9-8bf3-bc97eb767c35.PNG)

**Comment by fliegera** [comment]
If I uninstall the Serverless Operator and manually install the Knative Seving Operator from the community the tutorial examples work fine

**Comment by kameshsampath** [comment]
@fliegera - I seeing that happening off late .. earlier I used to see `knative-serving` project created and components deployed.  Would mind trying to create the CR https://github.com/redhat-developer-demos/knative-tutorial/blob/master/install/knative-serving/cr.yaml ? If that works I can then add creation of cr to the docs

**Comment by fliegera** [comment]
I also saw this file and tried to apply it, but it failed. I try to rcreate the cluster and will com back to you.

By the way, the command  **oc new-project knativetutorial**  is now missing in the description.

**Comment by kameshsampath** [comment]
ah thanks @fliegera  - will try to check these when am back at it

**Comment by fliegera** [comment]
**oc apply -f "$TUTORIAL_HOME/install/knative-serving/cr.yaml"**

Error from server (NotFound): error when creating "/home/xxx/knative-tutorial/install/knative-serving/cr.yaml": **namespaces "knative-serving"** not found

I beleive that the namespace (openshift-operators) given in https://github.com/redhat-developer-demos/knative-tutorial/blob/master/install/knative-serving/subscription.yaml is wrong

**Comment by kameshsampath** [comment]
@fliegera  - please check the latest docs for all updated instructions. I am closing this issue after validating it. Please feel free to reopen if you still see there are issues.
