### ISSUE TITLE
Starting che workspace comes up with error

### ISSUE THREAD

**Issue by fliegera** [redhat-developer-demos/knative-tutorial#193]
chectl workspace:start -f $TUTORIAL_HOME/devfile.yaml

comes up with the follwoing error

>   √ Retrieving Che Server URL...http://che-che.apps-crc.testing
  √ Verify if Che server is running...RUNNING (auth enabled)
  × Create workspace from Devfile C:\Users\AFG\Redhat\knative-tutorial/devfile.yaml
    → E_AUTH_REQUIRED - Che authentication is enabled and an access token need to be provided (flag --access-token).
 »   Error: E_AUTH_REQUIRED - Che authentication is enabled and an access token need to be provided (flag --access-token).

**Comment by kameshsampath** [comment]
Thanks for pointing we need to get the token, will be updating in next release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kameshsampath** [comment]
@fliegera  - you need to use the `oc whoami --show-token` and use that as parameter to chectl. Also please be sure to update to the latest. Closing this for now and please reopen if you still face the issue.
