### ISSUE TITLE
Different project name than knativetutorial

### ISSUE THREAD

**Issue by fliegera** [redhat-developer-demos/knative-tutorial#194]
I am on an Openshift Cluster with multiple users installed.

Whenever I create a project with a name different from **knativetutorial** and I apply the service.yaml

then run the command 

oc --namespace <myprojectname> get services.serving.knative.dev <name>

The created Service remains in Status **Uninitialized** forever

**Comment by kameshsampath** [comment]
When creating new projects the project needs an entry in Isito ServiceMemberRoll for it work. That should fix your problem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fliegera** [comment]
Ah. And where need I perform this configuration?

**Comment by fliegera** [comment]
FollowUp. The same seems to be with the name of the service if I use a different name than greeter the Status remains **Uninitialized** forever

**Comment by fliegera** [comment]
I now added the project to ServiceMemberRoll under istio-system namespace -> All Instances.

When I now create a new project the Operators gets copied into my namespace but the ServiceMemberRoll  of the copied Operator remains empty.

The problem remains still the same, it does not work at all for me.

The users created are in the role bsic-user.

**Comment by kameshsampath** [comment]
ServiceMemberRoll in istio-system is what needed. It need not be created in all ns

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kameshsampath** [comment]
Not sure this is still valid as Knative in OCP has its own ingress and the project should not be in Istio SMMR
