### ISSUE TITLE
kn create service XXX Unauthorized error

### ISSUE THREAD

**Issue by karimbzu** [redhat-developer-demos/knative-tutorial#195]
I am trying to run this command
#kn service create greeter --namespace knativetutorial --image quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

the following error appears:
#Unauthorized

Kindly help me in this regard

**Comment by kameshsampath** [comment]
Are you on OpenShift?? If so then you have not logged in

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
