### ISSUE TITLE
Hey tool requires -host instead than -H "Host:"

### ISSUE THREAD

**Issue by pdettori** [redhat-developer-demos/knative-tutorial#197]
**Describe the bug**
I have been following the Knative scaling tutorial, but had issues with the command:
```
hey -c 50 -z 10s   -H "Host:prime-generator.knativetutorial.example.com"   "http://${IP_ADDRESS}/?sleep=3&upto=10000&memload=100"
```
Looking into hey docs, it looks like to set the Host header one has to use -host. 

**To Reproduce**
1. Follow the Knative serving scaling tutorial, and try to run it up to the `hey -c 50 ... ` command. 
2. Verify that no pods are created and all responses have 404 HTTP code

**Expected behavior**
Pods are created and scaling happens

The Expected Behavior happens if I use the following command instead:

```
hey -c 50 -z 10s -host "prime-generator.knativetutorial.example.com" "http://${IP_ADDRESS}/?sleep=3&upto=10000&memload=100"
```

**Comment by kameshsampath** [comment]
fixed in the latest docs. Please feel free to reopen if you sill see the issue
