### ISSUE TITLE
Event Source requires sink deployed before starting container

### ISSUE THREAD

**Issue by pdettori** [redhat-developer-demos/knative-tutorial#198]
**Describe the bug**
The steps described for the Event Source tutorial for Native eventing provide directions for deploying the cronjob source and check for created pods in the knativetutorial namespace, however no pods are created and looking at the logs for sources-controller I see the following error:
```
{"level":"error","ts":"2020-01-07T01:59:26.137Z","logger":"source-controller.cronjob-source-controller","caller":"controller/controller.go:345","msg":"Reconcile error","knative.dev/controller":"cronjob-source-controller","error":"Error fetching sink &ObjectReference{Kind:Service,Namespace:knativetutorial,Name:event-greeter,UID:,APIVersion:serving.knative.dev/v1alpha1,ResourceVersion:,FieldPath:,} for source \"knativetutorial/event-greeter-cronjob-source, /, Kind=\": services.serving.knative.dev \"event-greeter\" not found" ...}
```
However, if I create the sink first by deploying the `event-greeter` service then the cronjobsource pod is correctly started. 

It seems that since the Event Source tutorial is describing a scenario where source and sink are directly connected, the tutorial would work best by asking to deploy the sink first and then the source.

**Comment by pdettori** [comment]
Seems like this is also noted in #184

**Comment by kameshsampath** [comment]
fixed in latest update
