### ISSUE TITLE
OCP 4.2 Serverless Operator installs Services mesh differently

### ISSUE THREAD

**Issue by alexgroom** [redhat-developer-demos/knative-tutorial#199]
The 4.2 Serverless Operator now installs Service Mesh itself and this seems to clash with the Tutorial instructions leading to an Istio conflict in the knative-serving project deployment.

First thing I notice is that the instruction are designed around 4.1 OCP but the new version of Serverless for 4.2 uses a different approach to install Service Mesh, it is now included as a sub component of the Serverless operator. This means the 4.1 based instructions in the tutorial are confusing and contradictory as indicated by the latest OCP docs for 4.1 compared to 4.2:

https://docs.openshift.com/container-platform/4.2/serverless/installing-openshift-serverless.html
https://docs.openshift.com/container-platform/4.1/serverless/installing-openshift-serverless.html

Having followed the tutorial instructions I end up with a service mesh error which I think is a result of installing Service mesh manually.

My Knative-serving operator in the Knative-serving project fails to start/run due to an Istio conflict and I believe this is the istio project that is explicitly created in the tutorial instructions:

Install failed with message: Could not add 'knative-serving' to ServiceMeshMemberRoll (SMMR) because it's already part of another SMMR, likely one in 'istio-system' (check with 'oc get smmr --all-namespaces'). Remove 'knative-serving' and all namespaces that contain Knative Services from that other SMMR

And sure enough, following the remedial action in the error message:

knative-tutorial agroom$ oc get smmr --all-namespaces
NAMESPACE      NAME      MEMBERS
istio-system   default   [knative-serving knative-eventing knativetutorial]

**Comment by kameshsampath** [comment]
the tutorial now points all OpenShift to upstream docs.
