### ISSUE TITLE
Run The CamelK Code

### ISSUE THREAD

**Issue by waytoharish** [redhat-developer-demos/knative-tutorial#200]
Hi,
How could i run the maven project from the CamelK in the getting Started-

To run Java Class or groovy we use Kamel Client-

kamel run helloworld.groovy

**Comment by kameshsampath** [comment]
the maven project was created just to help you with the IDE support when you develop. You actually dont use that when deploying camel-k integrations. All camel-k integrations are just single files.

**Comment by waytoharish** [comment]
So if we have a Dependent Java Files then how can we run that. For example-
Controller Class-  Service class-  Data Service all have Class1--> Class2--> Class3 
Then how to run all these

**Comment by kameshsampath** [comment]
Make them as dependency and add them as jar via —dependency. Note this has to be in a maven repo that is configured with camel-k. Camel-k maven settings is same namespace as you installed camel. Its a configmap called “camel-k-maven-settings”

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by waytoharish** [comment]
Ohh So i can not execute Spring-boot or quarkus based jar directly from Kamel ??
