### ISSUE TITLE
Update CoreDNS patch script failing

### ISSUE THREAD

**Issue by ghost** [redhat-developer-demos/knative-tutorial#203]
**Description**
Error with yq parsing the output of config map while running patch script to update coredns.

**To Reproduce**
1. Followed all the steps as is from knative tutorial till **Update CoreDNS**
2. Download yq source code and do `go install yq.go` to get the binary and add $GOPATH/bin to $PATH for system to be able to find yq.
3. Run the script patch-coredns.sh in $HOME/knative-tutorial/apps/minikube-registry-helper

**Expected behavior**
Should be patched successfully

**Current behaviour**
Script fails with the following error:
`Error from server (BadRequest): json: cannot unmarshal string into Go value of type map[string]interface {}`

**Desktop and tools specs**
 - OS - RHEL 8 x86_64 GNU/Linux
 - Shell - bash
 - Minikube version - 1.8.2
 - yq version - 3.2.1
 - kubectl version info - Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
 - go version - 1.14 linux/amd64

**Additional context**
Couldn't install yq thorough snap as there was some dependencies issues while building rpm to install snap therefore had to go with downloading the source code and go install.

**Comment by kameshsampath** [comment]
Yq should <= 3.x, yq 3 has breaking changes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghost** [comment]
@kameshsampath Thanks. That fixed the problem.
Please mention the cli tools version as well in the tutorial.

**Comment by kameshsampath** [comment]
the CLI tools already mentions that https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/setup.html

**Comment by ghost** [comment]
@kameshsampath Not here, it doesn't: https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-basics/0.7.x/01-setup.html#kubernetes-cluster

**Comment by kameshsampath** [comment]
Please use the latest one

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
