### ISSUE TITLE
Link "Canary Release" and "Service Visibility" in left menu are not working

### ISSUE THREAD

**Issue by sebastienblanc** [redhat-developer-demos/knative-tutorial#204]
These 2 links are not working : 

https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/traffic-distribution.html#canary-release

https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/traffic-distribution.html#service-visibility

**Comment by kameshsampath** [comment]
> These 2 links are not working :
> 
> https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/traffic-distribution.html#canary-release
> 
Fixed in latest docs
> https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/traffic-distribution.html#service-visibility
This is moved to Advanced section
