### ISSUE TITLE
"kn service describe greeter" doesn't output yaml by default

### ISSUE THREAD

**Issue by maschmid** [redhat-developer-demos/knative-tutorial#209]
**Describe the bug**
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/knative-client.html#kn-desc-ksvc

says

> 
> Sometime you wish you get the YAML of the Knative service to build a new service or to compare with with another service. kn makes it super easy for you to get the YAML:
> 
> kn service describe greeter

however, "kn service describe greeter" output (in version 0.12) is

```
$ kn service describe greeter

Name:       greeter
Namespace:  knativetutorial
Age:        9m
URL:        http://greeter.knativetutorial.apps.maschmid1.openshift-aws.rhocf-dev.net

Revisions:  
  100%  @latest (greeter-kqwzv-2) [2] (9m)
        Image:  quay.io/rhdevelopers/knative-tutorial-greeter:quarkus (pinned to 767e2f)

Conditions:  
  OK TYPE                   AGE REASON
  ++ Ready                   9m 
  ++ ConfigurationsReady     9m 
  ++ RoutesReady             9m 
```

("kn service describe greeter -o yaml" could be used to specifically output yaml. However, the tutorial should probably be updated to show the default output of "describe")

**Comment by maschmid** [comment]
Also here

https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/knative-client.html#kn-revisions-desc

```
kn revision describe greeter-jgrcx-2

        Name:       greeter-jgrcx-2
        Namespace:  knativetutorial
        Age:        8s
        Image:      quay.io/rhdevelopers/knative-tutorial-greeter:quarkus (pinned to 767e2f)
        Env:        MESSAGE_PREFIX=Namaste
        Service:    greeter
        
        Conditions:  
          OK TYPE                  AGE REASON
          ++ Ready                  4s 
          ++ ContainerHealthy       4s 
          ++ ResourcesAvailable     8s 
          ++ Active                 4s

```

**Comment by sebastienblanc** [comment]
fixed
