### ISSUE TITLE
Missing invocation content

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#215]
https://www.screencast.com/t/yj7fMGnf9PA

The invocation should be spelled out for the reader.  Many readers are ignoring the narrative/prose and simply using the obvious commands.   Therefore they will skip over the text "Invoking Service will now show an output like Namaste greeter ⇒ '6fee83923a9f' : 1, where Namaste is the value we configured via environment variable in the Knative service resource file."

and not actually invoke the service

**Comment by kameshsampath** [comment]
updated as part of upcoming release
