### ISSUE TITLE
Knative Eventing events through the Kafka Source must be JSON formatted

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#222]
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-adv/eventing-with-kafka.html#kn-eventing-kafka-source-to-sink

JSON formatting was removed from the example/docs as it is no longer a requirement.  We should double check this with Matthias W to be sure.

**Comment by kameshsampath** [comment]
@burrsutter IIRC that was the last requirement, if it has been channged again then we should. Adding @sebastienblanc
