### ISSUE TITLE
eval minikube docker-env fails with shrug emoji error ...

### ISSUE THREAD

**Issue by aslom** [redhat-developer-demos/knative-tutorial#226]
**Describe the bug**
`eval $(minikube docker-env)` fails with "shrug" emoji error ...

**To Reproduce**

```
$ eval $(minikube docker-env)
zsh: command not found: 🤷
$ minikube docker-env
🤷  The control plane node must be running for this command
👉  To fix this, run: "minikube start"
```

it is started and $TUTORIAL_HOME/bin/start-minikube.sh uses profile

to fix add profile from tutorial eval:

```
eval $(minikube -p knativetutorial docker-env)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aslom** [comment]
Other solution is to switch to knativetutorial as default with `minikube profile knativetutorial`

**Comment by kameshsampath** [comment]
@aslom  - the profile thing is going to be depreacated from minikube soon and starting with `-p <profile>` will automatically make that profile default in current shell. In other places its recommended to use `$(minikube -p docker-env)`,  just getting ready for deprecation

**Comment by aslom** [comment]
Update documentation until minikube is fixed - also people may be using old
version?

**Comment by kameshsampath** [comment]
the updates and new release happening in coming days will have it updated
