### ISSUE TITLE
kubernetes version out of sync

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#229]
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/basic-fundas.html#basics-prerequisite

says 
Client Version: v1.18.2
Server Version: v1.18.2

but the script to start minikube says
 --kubernetes-version=v1.15.0
https://github.com/redhat-developer-demos/knative-tutorial/blob/master/bin/start-minikube.sh#L21

**Comment by kameshsampath** [comment]
fixed in upcoming release to be 1.19.0
