### ISSUE TITLE
switch to scaling directory missing

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#230]
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/scaling.html#scaling-autoscaling-deploy-service
has the end-user try 
kubectl apply -n knativetutorial -f service-10.yaml
but does not tell them to 
cd ../scaling

they will be in "basics" based on the paragraphs above

**Comment by kameshsampath** [comment]
fixed it in upcoming release
