### ISSUE TITLE
missing channel cleanup

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#236]
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-eventing/channel-and-subscribers.html#eventing-cleanup

kubectl -n knativetutorial delete -f eventing-helloa-sink.yaml
kubectl -n knativetutorial delete -f eventing-helloa-sub.yaml
kubectl -n knativetutorial delete -f eventing-hellob-sink.yaml
kubectl -n knativetutorial delete -f eventing-hellob-sub.yaml
kubectl -n knativetutorial delete -f event-source.yaml
and
kubectl -n knativetutorial delete -f channel.yaml

**Comment by kameshsampath** [comment]
fixed in upcoming release
