### ISSUE TITLE
patch-coredns.sh fails at kubectl patch

### ISSUE THREAD

**Issue by sstults** [redhat-developer-demos/knative-tutorial#238]
**Describe the bug**
From Chapter 1.4 Configuring Container Registry Aliases, `./patch-coredns.sh` fails with "BadRequest".

**To Reproduce**
1. `cd $BOOK_HOME/apps`
2. `./patch-coredns.sh`
4. See error:
```bash
Error from server (BadRequest): json: cannot unmarshal string into Go value of type map[string]interface {}
```

After following the preceding steps in the tutorial and executing `./patch-coredns.sh`, data.Corefile still shows:

`kubectl get cm coredns -n kube-system -oyaml | yq r - data.Corefile`

```yaml
.:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```

**Expected behavior**
`kubectl get cm coredns -n kube-system -oyaml | yq r - data.Corefile`

```yaml
.:53 {
    errors
    health
    rewrite name dev.local registry.kube-system.svc.cluster.local
    rewrite name example.com registry.kube-system.svc.cluster.local
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        upstream
        fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.6

**Additional context**
Docker
`docker --version`
`Docker version 19.03.12, build 48a66213fe`

kubectl
`kubectl version --short`
```
Client Version: v1.16.6-beta.0
Server Version: v1.15.0
```
*Maybe the version mismatch is a source of the problem? Also, book references 1.15.0, so maybe changes in 1.16?*

helm
`helm version`
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

yq
`yq --version`
`yq version 3.3.2`

**Comment by kameshsampath** [comment]
we have moved to using registry-aliases addon , to this will not happen :)
