### ISSUE TITLE
Typesetting error in book misses single quotes when necessary

### ISSUE THREAD

**Issue by sstults** [redhat-developer-demos/knative-tutorial#239]
**Describe the bug**
In Chapter 4.7 Discussion, the command to set the environment variable to the name of the spammer pod is this:

```bash
KAFKA_SPAMMER_POD=$(kubectl -n kafka get pod -l "run=kafka-spammer" \
-o jsonpath={.items[0].metadata.name})
```

This will fail with:
`zsh: no matches found: jsonpath={.items[0].metadata.name}`

The issue appears to be that either double or single quotes are not surrounding the jsonpath value. 

**To Reproduce**
1. Go to Chapter 4.7 Discussion 
2. Select the text of the second command example starting with `KAFKA_SPAMMER_POD`
3. Paste the selected text into a shell prompt
5. Edit the command by surrounding the jsonpath with either single or double quotes
6. Execute the command
7. See proper output of the pod name

**Expected behavior**
When the command is copied from the book and pasted into a shell prompt it should include double or single quotes around the jsonpath parameter to `kubectl`.

**Screenshots**
Below is a screenshot of how the text appears in the PDF. The value of jsonpath appears to be typset in italics, which probably indicates that the quotes were misinterpreted as markup:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/93471/89857084-134bb880-db69-11ea-8e40-47e09044254a.png">

**Comment by sstults** [comment]
I got this to work by adding double quotes on the outside of the curly braces, and then a backslash `\` at the end of the first command so that the `KAFKA_SPAMMER_POD` environment variable is available to the `kubectl` command:

```bash
KAFKA_SPAMMER_POD=$(kubectl -n kafka get pod -l "run=kafka-spammer" -o jsonpath="{.items[0].metadata.name}") \
kubectl -n kafka exec -it $KAFKA_SPAMMER_POD -- /bin/sh
```

**Comment by kameshsampath** [comment]
fixed in upcoming release scheduled for Friday
