### ISSUE TITLE
Unable to run Knative Revision Commands

### ISSUE THREAD

**Issue by ksingh7** [redhat-developer-demos/knative-tutorial#241]
**Describe the bug**
Under knative  client > Knative revision commands are not work because in the previous step we have deleted the kn service

**To Reproduce**
1. go to https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/knative-client.html
2. follow the instructions one by one
3. go to Knative Revision Commands and run any command
4. all commands will fail, because in the last step service greeter has been deleted

**Comment by kameshsampath** [comment]
Karan, I think you missed this note https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/knative-client.html#kn-delete-ksvc; but thanks for pointing this out, I am fixing it in next release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kameshsampath** [comment]
this fixed in new release scheduled for Friday
