### ISSUE TITLE
Usage of 0.17.0

### ISSUE THREAD

**Issue by matzew** [redhat-developer-demos/knative-tutorial#243]
**Describe the bug**

For eventing the 0.17.0 was a bad release - lacking the `eventing.yaml`:
* https://github.com/knative/eventing/issues/3873
* https://github.com/knative/operator/pull/325

I'd recommend a higher version, than 0.17.0 (e.g. 0.17.2 - that's what we use for Serverless Operator)

**Comment by matzew** [comment]
IT's mentioned in here: https://redhat-developer-docs.github.io/knative-tutorial-staging/knative-tutorial/setup/minikube.html

**Comment by aliok** [comment]
Better use serving 0.17.4, eventing 0.17.8, net-kourier 0.17.2

**Comment by kameshsampath** [comment]
Thanks Ali, will do the needed updates

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
