### ISSUE TITLE
Hello -> Bonjour

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#25]
**Describe the bug**
Lets change Hello to Bonjour or Namaste, https://github.com/redhat-developer-demos/knative-tutorial/blob/master/01-basics/knative/service-env.yaml#L14 
As that would make it much more obvious to the reader.  Right now "Hi" to "Hello" is too subtle and easy for the audience to miss the point.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kameshsampath** [comment]
thanks @burrsutter  will have it fixed in next iteration.
