### ISSUE TITLE
Problem with command ==> export SVC_URL=`kubectl get rt greeter -o yaml | yq read - 'status.url'` && \ http $SVC_URL

### ISSUE THREAD

**Issue by carlosmonzon2008** [redhat-developer-demos/knative-tutorial#270]
I have faced an error with yq latest binary version "v4.6.3" yq_linux_amd64, [https://github.com/mikefarah/yq/releases/tag/v4.6.3](https://github.com/mikefarah/yq/releases/tag/v4.6.3), in my Debian.

Error: unknown command "read" for "yq"

The command for this version is:

**export SVC_URL=`kubectl get rt greeter -o yaml | yq eval '.status.url' -` && \
http $SVC_URL**

**Comment by kameshsampath** [comment]
Sorry for the inconvenience, YQ 4 has totally new syntax quite analogous to jq; hence please try with Yq 2.4.1,  https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/setup/setup.html#tools; I am planning to move them to YQ 4 or use jsonpath as part of upcoming releases.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: carlosmonzon2008 ***@***.***>
Sent: Saturday, April 10, 2021 4:34:25 AM
To: redhat-developer-demos/knative-tutorial ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [redhat-developer-demos/knative-tutorial] Problem with command ==> export SVC_URL=`kubectl get rt greeter -o yaml | yq read - 'status.url'` && \ http $SVC_URL (#270)


I have faced an error with yq latest binary version "v4.6.3" yq_linux_amd64, https://github.com/mikefarah/yq/releases/tag/v4.6.3<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmikefarah%2Fyq%2Freleases%2Ftag%2Fv4.6.3&data=04%7C01%7C%7C732cbac7554147f9403f08d8fbabd25d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637536062669475069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CpVNPHFl0D0yhJixJcoDlkFrHmPnsHN5pk%2F0bJGVyl8%3D&reserved=0>, in my Debian.

Error: unknown command "read" for "yq"

The command for this version is:

export SVC_URL=kubectl get rt greeter -o yaml | yq eval '.status.url' - &&
http $SVC_URL

**Comment by carlosmonzon2008** [comment]
> Sorry for the inconvenience, YQ 4 has totally new syntax quite analogous to jq; hence please try with Yq 2.4.1, https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/setup/setup.html#tools; I am planning to move them to YQ 4 or use jsonpath as part of upcoming releases. Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: carlosmonzon2008 ***@***.***> Sent: Saturday, April 10, 2021 4:34:25 AM To: redhat-developer-demos/knative-tutorial ***@***.***> Cc: Subscribed ***@***.***> Subject: [redhat-developer-demos/knative-tutorial] Problem with command ==> export SVC_URL=`kubectl get rt greeter -o yaml | yq read - 'status.url'` && \ http $SVC_URL (#270) I have faced an error with yq latest binary version "v4.6.3" yq_linux_amd64, https://github.com/mikefarah/yq/releases/tag/v4.6.3<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmikefarah%2Fyq%2Freleases%2Ftag%2Fv4.6.3&data=04%7C01%7C%7C732cbac7554147f9403f08d8fbabd25d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637536062669475069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CpVNPHFl0D0yhJixJcoDlkFrHmPnsHN5pk%2F0bJGVyl8%3D&reserved=0>, in my Debian. Error: unknown command "read" for "yq" The command for this version is: export SVC_URL=kubectl get rt greeter -o yaml | yq eval '.status.url' - && http $SVC_URL — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fredhat-developer-demos%2Fknative-tutorial%2Fissues%2F270&data=04%7C01%7C%7C732cbac7554147f9403f08d8fbabd25d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637536062669485062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zPuCrML83xdf0nPd6EGpPY%2FwV8v7R2ItvVF29LAsN6k%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHHMIO2TVNAC5MPYOFVWVDTH6BXTANCNFSM42VZ6DHA&data=04%7C01%7C%7C732cbac7554147f9403f08d8fbabd25d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637536062669485062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kapAAooDDQz1Zg5VT4M34rCoitkS31rwx9RvTbvP7zk%3D&reserved=0>.

No problem. Thank you Kamesh.
If you want, you just need to indicate the compatible version for the commands, and put the commands for both versions.

The command I have indicated, is the one got working for version 4.

**export SVC_URL=kubectl get rt greeter -o yaml | yq eval '.status.url' - && \\
http $SVC_URL**

Can I close this issue then?

**Comment by kameshsampath** [comment]
Let me keep it open so that I can track to close in next release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
