### ISSUE TITLE
Fix typo in code snippet in file scaling.adoc#load-the-service

### ISSUE THREAD

**Issue by mmurphy** [redhat-developer-demos/knative-tutorial#274]
The code snippet in the  `#load-the-service` section of file /documentation/modules/serving/pages/scaling.adoc
in incorrect
```
export SVC_URL=$(kn service describe prime-generator -n{tutorial-namespace} -url)
```
should be
```
export SVC_URL=$(kn service describe prime-generator -n {tutorial-namespace} -o url)
```

**Comment by kameshsampath** [comment]
Yes another PR is in place to fix that. Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Martin Murphy ***@***.***>
Sent: Thursday, May 13, 2021 7:02:37 PM
To: redhat-developer-demos/knative-tutorial ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [redhat-developer-demos/knative-tutorial] Fix typo in code snippet in file scaling.adoc#load-the-service (#274)


The code snippet in the #load-the-service section of file /documentation/modules/serving/pages/scaling.adoc
in incorrect

export SVC_URL=$(kn service describe prime-generator -n{tutorial-namespace} -url)


should be

export SVC_URL=$(kn service describe prime-generator -n {tutorial-namespace} -o url)
