### ISSUE TITLE
Script install-istio.sh doesn't work for minikube 1.23.2

### ISSUE THREAD

**Issue by nicolasduminil** [redhat-developer-demos/knative-tutorial#281]
**Describe the bug**
Can't install istio on minikube 1.23 via the script `install-istio.sh.`
Here is the releases:

    $ minikube version
    minikube version: v1.23.2
    commit: 0a0ad764652082477c00d51d2475284b5d39ceed
    
    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2",   GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

    $ kubectl api-resources --api-group=apiextensions.k8s.io -o wide
    NAME                        SHORTNAMES   APIVERSION                NAMESPACED   KIND                       VERBS
    customresourcedefinitions   crd,crds     apiextensions.k8s.io/v1   false        CustomResourceDefinition   [create delete deletecollection get list patch update watch]

**To Reproduce**
1. Run `$BOOK_HOME/bin/install-istio.sh`
2. See error:

    unable to recognize "install/kubernetes/helm/istio-init/files/crd-10.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

**Expected behavior**
The script runs without error and istio gets installed

**Comment by sebastienblanc** [comment]
@lordofthejars @ammbra This is not needed anymore, right ?

**Comment by ammbra** [comment]
Yes, the script is not needed anymore.

**Comment by ammbra** [comment]
This issue was resolved by PR #285
