### ISSUE TITLE
Fix **Brokers and Triggers** section about using the correct filter for each event trigger

### ISSUE THREAD

**Issue by claudio4j** [redhat-developer-demos/knative-tutorial#287]
Fix **Brokers and Triggers** section about using the correct filter for each event trigger (aloha and bonjour)

The doc sets the filter as `greeting` for both triggers, but in the **Verification** section, uses either `aloha` or `bonjour` type to post the payload. The trigger section should set filter types as `aloha` or `bonjour`.

Another issue is in the **Verification** section, it uses the trigger service url, this way the curl payload is sent directly to the service bypassing the trigger filter. It should be fixed to use the broker url.

https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/eventing/eventing-trigger-broker.html#eventing-trigger

This behavior was observed for knative 1.1

**Comment by ammbra** [comment]
Thank you for spotting the issue in the curl requests. 

For this example, both triggers use the same filter type attribute, and thanks to your comment, it was replaced in the curl commands accordingly. Regarding the broker url comment, please check the last curl example in the verification section as that one uses the broker url in the curl command.

**Comment by claudio4j** [comment]
The `trigger/helloaloha` and `trigger/hellobonjour` has the same filter attribute `type: greeting`, it is my understanding of this tutorial was to show how a broker with filtering capabilities is to be used to actually direct payloads to different services, but this section shows the payload is sent *directly* to both services, that's why I think sending the payload to the broker and not to the services, will demonstrate the filtering capabilities.

See if this helps https://github.com/redhat-developer-demos/knative-tutorial/pull/289

**Comment by ammbra** [comment]
Ah, I misunderstood your previous comment. I will reopen the issue and review your PR tomorrow 😃 
Thank you very much for contributing to our tutorial 🙏
