### ISSUE TITLE
Update Camel K docs to use Kamelets instead of CamelSource

### ISSUE THREAD

**Issue by claudio4j** [redhat-developer-demos/knative-tutorial#291]
CamelSources are outdated and Kamelets should be used instead.

https://knative.dev/docs/eventing/sources/apache-camel-source/

**Comment by ammbra** [comment]
There was a small issue with the source of GitHub actions and now all is good.

**Comment by claudio4j** [comment]
I think there is a confusion about the github action you mentioned with this particular issue, they are not related.
