### ISSUE TITLE
Various minor issues

### ISSUE THREAD

**Issue by jamesfalkner** [redhat-developer-demos/knative-tutorial#4]
Ran across several small issues I was able to resolve (this is on a Mac) but you might consider fixing:

Setup->Prerequisites
-----
* When you `go get -u github.com/rakyll/hey` you can't run `hey` unless `$HOME/go/bin` is on your `$PATH`. Might consider mentioning this.
* When I installed knative-serving, the `activator` and `autoscaler` pods crashlooped for 10 minutes. If I killed the pods they then came back and started up properly. 

Basics and Fundamentals
-----
* Under "deploy service" (and a few other places) you have text `Navigate to folder $TUTORIAL_HOME/01-basics/knative` in text form. In other places you have the copy-and-pasteable `cd $TUTORIAL_HOME/...`. Suggest you always use the copy-and-pasteable command (I missed it and got file not found errors later, because I was looking for gray boxes with copy/paste commands)
* Under "service pinned to revision 1" you have a command `cd $TUTORIAL_HOME/knative` which doesn't work (and is not needed, since I'm already in the right directory at this point)

Configurations and Routes
-----
* At the start of this and other sections, you have me re-clone the source for `knative-tutorial-greeter` and re-build the project - but I already did that so you might want to say "If you have already cloned the repo and built the greeter service, you can skip" - otherwise you get errors `fatal: destination path 'knative-tutorial-greeter' already exists and is not an empty directory.`

Scaling
-----
* In "Calculating scale to zero time period", you have commands to set `stableWindow` and `scaleToZeroGracePeriod` - suggest you use UPPER_CASE names (like you do for other env vars) as I didn't think these were commands I was supposed to run. It looked like a text snippet.
* Bash Comment in the "Reset scale to zero to defaults" reads `# should return 2m` but the text above it says it should return `30s`.
* `watch` is not built into Mac OS X but can be installed with `brew install watch` - need to add that to the prereqs in the first section.

Build
-----
* Prerequisites: you may want to mention that not only do you need a docker hub account, you need to create a repository in your docker hub account (and use the name of the repository in the image name during build creation)
* The first command with `jsonnet` fails as I'm not in the right directory.  you need to add instructions to `cd $TUTORIAL_HOME/04-build/knative/templates`
* Under "Apply pre-requisite resources" you need to instruct them to `cd $TUTORIAL_HOME/04-build/knative` otherwise I'm still in the `templates/` subdir and none of the files exist when I run `oc apply` commands
* Under "See what you have deployed" - when I run `oc -n knativetutorial get builds.build.knative.dev event-greeter` I get an error (does not exist). I think you meant `oc -n knativetutorial get builds.build.knative.dev docker-build` ?
* Just a comment - nice to see knative build caches Maven dependencies :)
* When the service is accessed in the last step, the response for me is:

```json
{"message":"test message","host":"Event greeter => 'event-greeter-00001-deployment-7446845c4c-f5r79' : 2 ","time":"22:10:44"}
```

But the instructions say something about `unknown` which is confusing.

Build Template
----------------
* Malformed command (markdown error I think) under "Generate Build Template" for jsonnet
* Need to instruct users to `cd $TUTORIAL_HOME/04-build/knative/templates` before starting
* In the "Apply Resources" section, need to tell them to backup a directory (where the yamls are), or just `cd $TUTORIAL_HOME/04-build/knative`

Fantastic tutorial!

**Comment by kameshsampath** [comment]
oh @jamesfalkner  thanks so much for reporting . All my next week is for fixing grammar, typos etc., will address them.

**Comment by kameshsampath** [comment]
@jamesfalkner  - fixed most the comments. thanks for reporting much appreciated.

Some comments inline
* > When I installed knative-serving, the `activator` and `autoscaler` pods crashlooped for 10 minutes. If I killed the pods they then came back and started up properly.

this sometimes happens with upstream builds, but they are not consistently reproducible

* > Malformed command (markdown error I think) under "Generate Build Template" for jsonnet

did not get this, but still tried to fix if they space kind of thing is there

* > Prerequisites: you may want to mention that not only do you need a docker hub account, you need to create a repository in your docker hub account (and use the name of the repository in the image name during build creation)

Creating the docker hub account will give you a repo under the username, so thought to avoid that extra mention

Please verify it when you are at it next time and let me know.

**Comment by kameshsampath** [comment]
@jamesfalkner  - the changes are updated in the doc via #10 . Please validate when you are at it
