### ISSUE TITLE
Upgrade to Knative v0.4

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/knative-tutorial#42]
Upgrade the Knative installation to use v0.4

**Comment by kameshsampath** [comment]
As the upgrade v.0.4.0 has lot of breaking changes, it better to have all functionalities throughly checked

**Comment by kameshsampath** [comment]
@burrsutter  - please add anything that you want to check specifically

**Comment by bbrowning** [comment]
cc @lberk - based on some Slack discussions it sounds like you may be looking at both this tutorial and 0.4 in the near future :)

**Comment by kameshsampath** [comment]
@lberk - thanks

**Comment by lberk** [comment]
@bbrowning @kameshsampath Please see [PR77](https://github.com/redhat-developer-demos/knative-tutorial/pull/77) for some fixes to help get the tutorial working on 0.4.0

**Comment by rhuss** [comment]
One issue I have with 0.4.0 is that the revision names are not predictable. I.e. its not [`greeter-0001`](https://github.com/redhat-developer-demos/knative-tutorial/blob/a1302d9c2554495e455b7c383ddb0098c334dd8b/01-basics/knative/service-pinned-rev1.yaml#L7) as used in the tutorial but a random suffix, which you can't easily predict in advance and added to the service's `revisions` array.

I think [this part](https://github.com/redhat-developer-demos/knative-tutorial/blob/master/documentation/modules/ROOT/pages/01basic-fundas.adoc#deploy-new-revision-service) of the tutorial talking about 'pinned revisions' needs serious rework for 0.4.0 as there is no static revision which you can pre-add in deployment descriptor.

**Comment by lberk** [comment]
@rhuss strategies for this was discussed earlier today, one option is changing the tutorial so that we properly use the randomly generated revision names.  @syedriko also mentioned using generation number (annotations I think?) might be a solution

**Comment by bbrowning** [comment]
You can get the latest created revision for any Knative Service with a kubectl command like:

```shell
kubectl get ksvc my-knative-service -o jsonpath="{.status.latestCreatedRevisionName}"
```
The tutorial will need to be changed to lookup this latest revision name and do a substitution in the yaml stored in the tutorial repo before applying it.

**Comment by rhuss** [comment]
@kamesh you could introduce a shell function like 

```bash
function latest_revision() {
   local name=${1}
   local revision=$(kubectl get ksvc $name -o jsonpath="{.status.latestCreatedRevisionName}")
   echo "${name}-${revision}"
}
```

and then use it like in 

```bash
kubectl get $(latest_revision my-knative-service)
```

You get the idea.

**Comment by kameshsampath** [comment]
@rhuss  we fixed this by querying revisions directly with labels and sort by creation stamp ( thanks to @markusthoemmes  @bbrowning ) . I have added them to the tutorial. you should see them in next release.
