### ISSUE TITLE
Add codebox or tabs instead of OR

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/knative-tutorial#45]
currently there are may places where we do `(OR)` for showing two different code pieces. It better we have use better way like codebox/tabs to handle them.

Refer https://github.com/couchbase/docs-site

**Comment by rhuss** [comment]
I thought a bit about this, and now that I'm working my way through the tutorial I really believe that the decision whether one runs the tutorial with Kubernetes *or* OpenShift happens very early.

That means, having everything intermixed is sub-optimal, even when you switch via tabs and codeboxes. The danger is also that you always have to click for every example to come to the second page (e.g. OpenShift).

Also, some screenshots are relevant for OpenShift or Kubernetes only (like that of the OpenShift console).

I suggest instead the following solution, which should be even easier to implement:

Generate two different sets of documentation and store them on different branches which name indicate version + type (e.g. 1.0.0-kubernetes and 1.0.0-openshift). This then can be selected by the combobox in the menu (as it is now for the different versions), and also from the Main page for different entry points.

As soon as you have selected the flavour, you stay within this tree. This would remove a lot of distraction and duplication.

'happy to help to implement this.

**Comment by kameshsampath** [comment]
right now the couchbase documentation https://docs.couchbase.com/home/index.html does this via plugin lib. I was exploring that and then wanted to finish the upgrade v0.4.0 and  then get into it. It will be great if you help me here.

**Comment by rhuss** [comment]
Do you mean for a top-level "kubernetes/openshift" selection in the navbar of for individual selection on the examples ? As mentioned above I'm all for a top-level switch to switch *all* boxes by a single selection. This is much more straight forward and easier to use.
