### ISSUE TITLE
How do I avoid always getting prompt for Use insecure connections?

### ISSUE THREAD

**Issue by csantanapr** [redhat-developer-demos/knative-tutorial#5]
**Describe the bug**
How do I avoid always getting prompt for` Use insecure connections?`

**To Reproduce**
1. install mnishift with brew
2. setup minishift following steps

3.
👽 $ oc login -u admin -p admin
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): yes

**Expected behavior**
I expect if I answer yes, I never get prompted ever again.
How do I avoid it?

**Desktop (please complete the following information):**
 - Mac Mojave

**Comment by kameshsampath** [comment]
the OpenShift and Kubernetes documents has instructions to apply new certificates.
