### ISSUE TITLE
mvn clean package

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#51]
**Describe the bug**
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/1.0-SNAPSHOT/02configs-and-routes.html#ctrd-build-containers

mvn clean package is referenced in the docs for the greeter service. 
BUT the greeter service currently has an interesting mvn build in its Dockerfile.

I would prefer to move away from the Docker-based mvn build because it is slow, especially in that "change some code, rebuild the docker image" mode that most developers live in.

**Comment by kameshsampath** [comment]
done in latest fixes.
