### ISSUE TITLE
Use latest release tag of openshift-cloud-functions/knative-operators

### ISSUE THREAD

**Issue by maschmid** [redhat-developer-demos/knative-tutorial#54]
**Describe the bug**

Installation on OpenShift should use the latest release of the knative-operators script

(which is currently tag "openshift-v0.3.0" )

See also https://github.com/openshift-cloud-functions/Documentation/blob/master/knative-OCP-4x.md  for the specific instructions which can probably be copy-pasted there)

**Comment by kameshsampath** [comment]
we will move the Operators based install via console like https://vimeo.com/336830627
