### ISSUE TITLE
kubectl -n knative-serving get configmaps config-autoscaler -o yaml | yq r - data.stable-window

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#55]
**Describe the bug**
This script no longer works with 0.4
kubectl -n knative-serving get configmaps config-autoscaler -o yaml | yq r - data.stable-window
it returns "null"

This one also returns null
kubectl -n knative-serving get configmaps config-autoscaler -o yaml |
 yq r - data.scale-to-zero-grace-period

In the docs at this point:
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/1.0-SNAPSHOT/03scaling.html#scaling-build-containers

**Comment by lberk** [comment]
This will be fixed once https://github.com/redhat-developer-demos/knative-tutorial/pull/77 is merged.

**Comment by kameshsampath** [comment]
@lberk  - shall we close this ?

**Comment by lberk** [comment]
@kameshsampath I'm not sure.  My originally proposed fix in #77 was not merged.  I've now cherry picked that commit and dropped the namespacing stuff for your consideration in #105
