### ISSUE TITLE
kubectl get revision no longer shows greeter-00001

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#56]
**Describe the bug**
As of Knative 0.4, revisions now have random names like
greeter-qcmmv   
greeter-vs7mt   

These areas in the docs and the sample yaml files are no longer accurate
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/1.0-SNAPSHOT/01basic-fundas.html#basics-pinning-revision
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/1.0-SNAPSHOT/02configs-and-routes.html#crtd-distributing-traffic

https://github.com/redhat-developer-demos/knative-tutorial/blob/master/01-basics/knative/service-pinned-rev1.yaml

https://github.com/redhat-developer-demos/knative-tutorial/blob/master/01-basics/knative/service-pinned-rev2.yaml

https://github.com/redhat-developer-demos/knative-tutorial/blob/master/02-configs-and-routes/route/route_rev1-10_rev2-90.yaml

**Comment by kameshsampath** [comment]
Fixed in latest master
