### ISSUE TITLE
containerConcurrency: 10

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#57]
https://screencast.com/t/wCA48uWuX9UM

From this document:
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/1.0-SNAPSHOT/03scaling.html#scaling-build-containers

**Comment by kameshsampath** [comment]
as this is open bug with knative and not sure on the timeline of completion. I will keep it open and will not fix now,

**Comment by bbrowning** [comment]
@kameshsampath Do you have any more info on the specific bug here? @markusthoemmes is our man for getting any upstream bugs fixed in knative autoscaling

**Comment by kameshsampath** [comment]
@bbrowning  - this is related to auto scaling when containerConcurrency being set. When we run the scale test the  number of scaled pods  != total requests / containerConcurrency. When I discussed this with @markusthoemmes  long time back he said the serving sets a default `containerConcurrency=10` . I did had slack discussion with @markusthoemmes on this couple of days back when he said that this not going to be fixed quickly in upstream

**Comment by markusthoemmes** [comment]
I assume the bug that's referenced here is https://github.com/knative/serving/issues/2579?
