### ISSUE TITLE
Getting errors when installing istio unable to recognize "STDIN"

### ISSUE THREAD

**Issue by csantanapr** [redhat-developer-demos/knative-tutorial#6]
**Describe the bug**
Getting errors when installing istio

**To Reproduce**
Run Command from here
https://github.com/redhat-developer-demos/knative-tutorial/blob/master/documentation/modules/ROOT/pages/setup.adoc#install-istio
```
curl -L https://github.com/knative/serving/releases/download/v0.3.0/istio.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | kubectl apply --filename -
```

**Expected behavior**
Clean install

**Screenshots**

$ curl -L https://github.com/knative/serving/releases/download/v0.3.0/istio.yaml \
>   | sed 's/LoadBalancer/NodePort/' \
>   | kubectl apply --filename -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   601    0   601    0     0   1987      0 --:--:-- --:--:-- --:--:--  1990
100  113k  100  113k    0     0   187k      0 --:--:-- --:--:-- --:--:-- 1448k
namespace/istio-system created
configmap/istio-galley-configuration created
configmap/istio-statsd-prom-bridge created
configmap/istio-security-custom-resources created
configmap/istio created
configmap/istio-sidecar-injector created
serviceaccount/istio-galley-service-account created
serviceaccount/istio-egressgateway-service-account created
serviceaccount/istio-ingressgateway-service-account created
serviceaccount/istio-mixer-service-account created
serviceaccount/istio-pilot-service-account created
serviceaccount/istio-cleanup-secrets-service-account created
clusterrole.rbac.authorization.k8s.io/istio-cleanup-secrets-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-cleanup-secrets-istio-system created
job.batch/istio-cleanup-secrets created
serviceaccount/istio-citadel-service-account created
serviceaccount/istio-sidecar-injector-service-account created
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceentries.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/httpapispecbindings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/httpapispecs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotaspecbindings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotaspecs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/rules.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/attributemanifests.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/bypasses.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/circonuses.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/deniers.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/fluentds.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/kubernetesenvs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/listcheckers.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/memquotas.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/noops.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/opas.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/prometheuses.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/rbacs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/redisquotas.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/servicecontrols.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/signalfxs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/solarwindses.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/stackdrivers.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/statsds.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/stdios.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/apikeys.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/authorizations.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/checknothings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/kuberneteses.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/listentries.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/logentries.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/edges.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/metrics.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotas.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/reportnothings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/servicecontrolreports.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/tracespans.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/rbacconfigs.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceroles.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/servicerolebindings.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/adapters.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/instances.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/templates.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/handlers.config.istio.io created
clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-egressgateway-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-ingressgateway-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-mixer-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-citadel-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-sidecar-injector-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-galley-admin-role-binding-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-egressgateway-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-ingressgateway-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-mixer-admin-role-binding-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-citadel-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-sidecar-injector-admin-role-binding-istio-system created
service/istio-galley created
service/istio-egressgateway created
service/istio-ingressgateway created
service/istio-policy created
service/istio-telemetry created
service/istio-statsd-prom-bridge created
deployment.extensions/istio-statsd-prom-bridge created
service/istio-pilot created
service/istio-citadel created
service/istio-sidecar-injector created
deployment.extensions/istio-galley created
deployment.extensions/istio-egressgateway created
deployment.extensions/istio-ingressgateway created
deployment.extensions/istio-policy created
deployment.extensions/istio-telemetry created
deployment.extensions/istio-pilot created
deployment.extensions/istio-citadel created
deployment.extensions/istio-sidecar-injector created
horizontalpodautoscaler.autoscaling/istio-egressgateway created
horizontalpodautoscaler.autoscaling/istio-ingressgateway created
horizontalpodautoscaler.autoscaling/istio-policy created
horizontalpodautoscaler.autoscaling/istio-telemetry created
horizontalpodautoscaler.autoscaling/istio-pilot created
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector created
serviceaccount/cluster-local-gateway-service-account created
clusterrole.rbac.authorization.k8s.io/cluster-local-gateway-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/cluster-local-gateway-istio-system created
service/cluster-local-gateway created
deployment.extensions/cluster-local-gateway created
horizontalpodautoscaler.autoscaling/cluster-local-gateway created
unable to recognize "STDIN": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "STDIN": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "stdio" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "logentry" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "logentry" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "prometheus" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "kubernetesenv" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
unable to recognize "STDIN": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"

**Desktop (please complete the following information):**
 - Mac Mojave

**Comment by kameshsampath** [comment]
@csantanapr  this is a known issue with istio, the warnings are reported because the CRDs does not exist already, if you are apply it the errors will go off.

**Comment by csantanapr** [comment]
Yeah I ran a second time and it worked. Worth adding a note for the user to try again if it’s see this type of errors

**Comment by kameshsampath** [comment]
sure will add it.

**Comment by kameshsampath** [comment]
@csantanapr  I just saw that I have already had that comment as part of "NOTES" https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/dev/setup.html#install-istio
