### ISSUE TITLE
resource constraints

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#63]
our default Knative Serving Services must have resource constraints.  The upstream default is 400m for CPU which means you can not auto-scale, 2 or more times.

Example of constraints 
https://github.com/burrsutter/sidebyside/blob/master/nodejs/knService.yml#L14

upstream issue:
https://github.com/knative/serving/issues/3434

**Comment by sebastienblanc** [comment]
@kameshsampath Was this issue opened before you wrote `./start-minikube` ? I just replayed the tutorial I did not encounter resources issue on minikube, so I think this one can be closed.

**Comment by kameshsampath** [comment]
Think so. Lets close it and open when needed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
