### ISSUE TITLE
Simplify Build Section

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/knative-tutorial#65]
Right now the build section has lots of jsonnet usage,  it will be nice to simplify it with simple yamls. One of the options to consider using https://github.com/kubernetes-sigs/kustomize.

CC: @burrsutter

**Comment by burrsutter** [comment]
Ideally, provide yamls that "just work" without editing.
Then provide yamls that are easy to edit for simple things like my docker id, my github repo, my image tag, my image name.
Templating is useful, as an "advanced" exercise once people have had success with their first helloworld of Knative Build
