### ISSUE TITLE
How do I setup minishift to kubectl?

### ISSUE THREAD

**Issue by csantanapr** [redhat-developer-demos/knative-tutorial#7]
**Describe the bug**
How do I setup minishift to kubectl?

**To Reproduce**
I see a lot of commands like `oc get pods`

I want to use `kubectl get pods`

**Comment by csantanapr** [comment]
Well my question is how do I switch my kubectl to use other cluster like remote ones and then openshift local with minishift?

**Comment by kameshsampath** [comment]
well you dont need to do anything extra for this work. Any kubectl command will work with minishift. But for login you need to use `oc` ( as this updates the ~/.kube/config file with needed tokens); then you can use oc and kubectl interchangably.

For connecting to remote servers you might need to add `--server` option to the oc login command

e.g `oc login -u admin -p admin --server https://192.168.1.10:8443`
