### ISSUE TITLE
Use aws cli profiles

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/knative-tutorial#71]
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
Users may already have an AWS configuration they wish to keep, so setup a profile for this local minio-based S3

https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/1.0-SNAPSHOT/camelk/setup.html#camelk-prerequisite

aws configure
# AWS Access Key ID [None]: demoaccesskey 
# AWS Secret Access Key [None]: demosecretkey 
# Default region name [None]:
# Default output format [None]:

aws configure set default.s3.signature_version s3v4 

aws configure list

**Comment by kameshsampath** [comment]
This is no longer in the tutorial . closing it
