### ISSUE TITLE
How do I use the tutorial using newer version of kubernetes like 1.12 or 1.13

### ISSUE THREAD

**Issue by csantanapr** [redhat-developer-demos/knative-tutorial#8]
**Describe the bug**
I want to use kubernetes 1.13 with the turorial

**To Reproduce**
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://192.168.99.100:8443
kubernetes v1.11.0+d4cacc0

Tutorial setups up 1.11, but I want to use 1.13

**Comment by kameshsampath** [comment]
with minishift it is possible only to use the kubernetes version thats part of the specific OpenShift release. TBH the instructions work well with any kubernetes version that Knative support. Thats the precise reason I would have given `kubectl` commands along with all `oc` commands in all places where its applicable.

**Comment by csantanapr** [comment]
Hmm might be good to replace “oc” for kubectl then, just my 2 cents

**Comment by kameshsampath** [comment]
if you seen your tutorial we follow the pattern to make it work for both OpenShift and Kubernetes so its worth keeping those sets in place and allow the user to choose what they want.

**Comment by csantanapr** [comment]
Having both is ok, but here are most of the places uses “oc” so the user might not in which instances using kubectl is ok to use.

**Comment by kameshsampath** [comment]
the latest docs has minikube for all devboxes and recommends to use latest minikube
