### ISSUE TITLE
Hardcoded minishift in 02-configs-and-routes/bin/call.sh

### ISSUE THREAD

**Issue by syedriko** [redhat-developer-demos/knative-tutorial#81]
**Describe the bug**
Hardcoded minishift in 02-configs-and-routes/bin/call.sh makes the script not so useful with minikube

**To Reproduce**
Run 02-configs-and-routes/bin/call.sh against minikube

**Expected behavior**
02-configs-and-routes/bin/call.sh works both against minishift and minikube or we have separate scripts for these two environments.

**Comment by kameshsampath** [comment]
yes thats something need to be fixed, thanks for add a issue

**Comment by kameshsampath** [comment]
I would prefer to have a snippet in the doc and let user use it copy and pasting ?? @syedriko thoughts??

**Comment by syedriko** [comment]
We can look at https://github.com/openshift-cloud-functions/knative-operators/blob/master/etc/scripts/installation-functions.sh for inspiration:

CMD=kubectl
if hash oc 2>/dev/null; then
  CMD=$_
fi

**Comment by kameshsampath** [comment]
this section will be removed soon. so closing it.
