### ISSUE TITLE
Make jsonnet more easily available on Fedora (and RHEL?)

### ISSUE THREAD

**Issue by syedriko** [redhat-developer-demos/knative-tutorial#82]
Jsonnet doesn’t seem to be available in default Fedora repos. I had to build it from C++ sources (here you go: https://drive.google.com/open?id=1ID_Lt9Xh6i66EMDN9ItBiZRQBnHVnqQi), but I've been building C++ sources most of my life. It might be an unfamiliar thing to do for some in the audience of the tutorial.

Can we may be find an equivalent tool that is in Fedora (and RHEL?) repos or help jsonnet get into those repos? It seems someone tried to get it there before
https://bugzilla.redhat.com/show_bug.cgi?id=1542522 , but the effort died off.

**Comment by kameshsampath** [comment]
@syedriko  - for the new upgrade for v0.4.0 I am going to remove Jsonnet with a simpler solution

**Comment by rhuss** [comment]
tbh, I think `jsonnet` usage in this tutorial can be replaced by plain `sed`.

**Comment by kameshsampath** [comment]
yes thats my plan too.

**Comment by kameshsampath** [comment]
I have removed the use of jsonnet completely from the tutorial, hence this bug is not relevant anymore.
