### ISSUE TITLE
Add "Copy to Clipboard" buttons

### ISSUE THREAD

**Issue by rhuss** [redhat-developer-demos/knative-tutorial#85]
It would be super awesome to have a "Copy to Clipboard" button on every example for CLI commands. 

The issue currently is, that its not only tedious to copy & paste manually but its also hard to select the proper line when you do double click (or CTRL-A), as often additional empty lines are being added to the clipboard which confuses the terminal when pasting (so you have to copy only that single line).

I'm not sure how easy it is to extend the Antora styles to include a corresponding JS library and adapt the default style for code example. Would be a good excercise to learn about asciidoctor extensions ;-)

**Comment by kameshsampath** [comment]
Closed via #116
