### ISSUE TITLE
Consider using internal registry for build examples

### ISSUE THREAD

**Issue by rhuss** [redhat-developer-demos/knative-tutorial#86]
Going over the Docker registry for the build examples has some drawbacks. The main is probably that you have to enter your Docker creds into a YAML/JSON file in plain text. This `docker-secret.yml` stays in the filesystem with default file permissions (typically world readable) and is not automatically cleaned up. 

Of course, one could even secure that more, but this de-focus the tutorial even further.

In https://github.com/k8spatterns/examples/blob/master/advanced/ImageBuilder/knative/README.adoc I tried a different approach, by installing an internal registry in minikube and using that. This example can't be used directly here, as it does not uses knative serving but a vanilla Deployment for running the image. But I felt much more comfortable to mangle yaml file to introduce the ClusterIP of the registry into the Deployment than storing Docker registry creds locally.

I think something similar can be done for this tutorial, too. For minishift, it should be even easier by reusing the OpenShift internal registry.

**Comment by kameshsampath** [comment]
@rhuss I idea was to show users that the can push to external registry and pull the image to use in the services.  I see your point on the security side of things. Will take this point in to consideration during the build chapter refactor

**Comment by kameshsampath** [comment]
having moved to tekton with #189  this will be using internal regsitries.
