### ISSUE TITLE
The Project menu is getting cut off

### ISSUE THREAD

**Issue by syedriko** [redhat-developer-demos/knative-tutorial#91]
**Describe the bug**
The Project menu items are not readable

**To Reproduce**
Open https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.0.0/index.html in a browser. Select the Project menu in the upper right corner.

**Expected behavior**
The Project menu items can be read

**Screenshots**
![tutorial_project](https://user-images.githubusercontent.com/48031344/55245215-161a6780-5219-11e9-8ba7-43f4e13b30f9.png)

**Desktop (please complete the following information):**
- OS: Fedora 29
- Browsers: Firefox 66, Chrome 73

**Comment by kameshsampath** [comment]
@syedriko  - i have a separate milestone for UI side of things  am not a an UI expert 😜, its already in my TODO

**Comment by kameshsampath** [comment]
the look and feel is changed now. There is no longer menu like this .
