### ISSUE TITLE
The "Knative Tutorial" link in the header is context-dependant

### ISSUE THREAD

**Issue by syedriko** [redhat-developer-demos/knative-tutorial#93]
**Describe the bug**
The "Knative Tutorial" link in the header is context-dependant and does not simply take to the starting page of the tutorial.

**To Reproduce**
Click any chapter header in the TOC, then click the "Knative Tutorial" link in the header.
For example, 2. Basics and Fundamentals
https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.0.0/01basic-fundas.html
Clicking the "Knative Tutorial" link takes to https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.0.0/01basic-fundas.html#

**Expected behavior**
The "Knative Tutorial" link in the header takes one to the starting page of the tutorial, https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.0.0/index.html

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser: Firefox 66, Chrome 73

**Comment by kameshsampath** [comment]
Closed via #100
