### ISSUE TITLE
./mvnw --version and other prereq version checks 

### ISSUE THREAD

**Issue by syedriko** [redhat-developer-demos/knative-tutorial#94]
**Describe the bug**
In a number of places, the tutorial refers to 
"./mvnw --version" out of context of a particular working directory.
There're also arguably excessive version checks of prerequisites in the beginning of every chapter.

**To Reproduce**
Follow the instructions on, for example, the https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/v1.0.0/03scaling.html#scaling-prerequisite page, run
./mvnw --version
where the tutorial asks too, get
[syedriko@localhost knative-tutorial]$ ./mvnw --version
bash: ./mvnw: No such file or directory
[syedriko@localhost knative-tutorial]$ 

**Expected behavior**
Either drop this version check completely (as well as the other version checks outside of the Prerequisite section in the beginning) or switch to calling 
"mvn --version" which is installed by the package manager and should be available on $PATH.

**Desktop (please complete the following information):**
 - OS: Fedora 29

**Comment by kameshsampath** [comment]
thanks @syedriko - i have pushed `mvnw` as part of the tutorial demos so we dont need to check it.

**Comment by kameshsampath** [comment]
Closed via #99
